# this file is for testing and verifying the FHIR service with two api endpoints
# ------------------------------------------------------------------------
# * requires the `vscode-httpyac` Visual Studio Code extension within IDE
#   or httpYac CLI when executing outside of the IDE
# * this service has 2 endpoints /Bundle/$validate & /Bundle/

@hostName = http://localhost:8080
{{
  // dotEnv is loaded by default so let's see if custom hostName is available;
  // if $HTTPYAC_HOST is available use it first otherwise use $HOST
  if(process.env.HOST) exports.hostName = process.env.HOST;
  if(process.env.HTTPYAC_HOST) exports.hostName = process.env.HTTPYAC_HOST;
}}

@contentType = application/json
@TECH_BD_FHIR_SERVICE_QE_IDENTIFIER = PARTNER1-TEST

### /metadata endpoint should return FHIR CapabilityStatement

GET {{hostName}}/metadata
Content-Type: {{contentType}}
?? status == 200
?? header content-type == text/html;charset=UTF-8
?? response.body  != null


### /Bundle/$validate should validate Test​ServiceRequest.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
?? status == 200
?? response.body  != null
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null

< Test​ServiceRequest.json

### /Bundle/$validate should validate TestTask.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
?? status == 200
?? response.body  != null
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null

< TestTask.json


### /Bundle/$validate should validate TestTaskCompleted.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
?? status == 200
?? response.body  != null
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null

< TestTaskCompleted.json

### /Bundle/$validate should validate Test​ProcedureCompleted.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
?? status == 200
?? response.body  != null
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null


< Test​ProcedureCompleted.json


### Bundle should validate and submit Test​ServiceRequest.json.json as @TECH_BD_FHIR_SERVICE_QE_IDENTIFIER
# DO NOT use any header variables which are not required by QEs
POST {{hostName}}/Bundle?include-incoming-payload-in-db=true HTTP/1.1
Content-Type: {{contentType}}
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
?? status == 200
?? response.body  != null

< Test​ServiceRequest.json
