# this file is for testing and verifying the FHIR service with two api endpoints
# ------------------------------------------------------------------------
# * requires the `vscode-httpyac` Visual Studio Code extension within IDE
#   or httpYac CLI when executing outside of the IDE
# * this service has 2 endpoints /Bundle/$validate & /Bundle/

@hostName = http://localhost:8080
{{
  // dotEnv is loaded by default so let's see if custom hostName is available;
  // if $HTTPYAC_HOST is available use it first otherwise use $HOST
  if(process.env.HOST) exports.hostName = process.env.HOST;
  if(process.env.HTTPYAC_HOST) exports.hostName = process.env.HTTPYAC_HOST;
}}

@contentType = application/json
@TECH_BD_FHIR_SERVICE_QE_IDENTIFIER = HEALTHELINK

@TECH_BD_INTERACTION_PERSISTENCE_FS = { "nature": "fs", "home": "TECHBD_INTERACTIONS" }
@TECH_BD_INTERACTION_PERSISTENCE_SFTP = { "nature": "sftp", arg1: "TODO" }
@TECH_BD_INTERACTION_PERSISTENCE_AWS_S3 = { "nature": "aws-s3", arg1: "TODO", arg2: "TODO" }

@TECH_BD_FHIR_SERVICE_STRUCT_DEFN_PROFILE_URI_SHINNY_SDOH = https://djq7jdt8kb490.cloudfront.net/1115/StructureDefinition-SHINNYBundleProfile.json

### /metadata endpoint should return FHIR CapabilityStatement

GET {{hostName}}/metadata
Content-Type: {{contentType}}
?? status == 200
?? header content-type == text/html;charset=UTF-8
?? response.body  != null

< fhir-fixture-shinny-impl-guide-sample.json

### /admin/observe/interaction/recent.json should contain HTTP request/response interactions

GET {{hostName}}/admin/observe/interaction/recent.json HTTP/1.1
?? status == 200
?? header content-type == application/json


### /Bundle/$validate should validate fhir-fixture-shinny-impl-guide-sample.json

POST {{hostName}}/Bundle/$validate HTTP/1.1 
Content-Type: {{contentType}}
Accept : application/fhir+json;charset=utf-8
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
X-TechBD-Interaction-Persistence-Strategy: {{TECH_BD_INTERACTION_PERSISTENCE_FS}}
X-TechBD-FHIR-Profile-URI: {{TECH_BD_FHIR_SERVICE_STRUCT_DEFN_PROFILE_URI_SHINNY_SDOH}}
?? status == 200
?? header content-type == application/fhir+json;charset=utf-8
?? response.body  != null
?? js response.parsedBody.OperationOutcome.validationResults[0].engine == HAPI
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == ERROR
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == 1
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == 6147

< fhir-fixture-shinny-impl-guide-sample.json


### /Bundle/$validate should validate fhir-fixture-unhappy-path-01.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
Accept : application/fhir+json;charset=utf-8
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
X-TechBD-Interaction-Persistence-Strategy: {{TECH_BD_INTERACTION_PERSISTENCE_FS}}
?? status == 200
?? header content-type == application/fhir+json;charset=utf-8
?? response.body  != null
?? js response.parsedBody.OperationOutcome.validationResults[0].engine == HAPI
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null

< fhir-fixture-unhappy-path-01.json


### /Bundle/$validate should validate fhir-fixture-shinny-bronx-unhappy-path.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
Accept : application/fhir+json;charset=utf-8
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
X-TechBD-Interaction-Persistence-Strategy: {{TECH_BD_INTERACTION_PERSISTENCE_FS}}
?? status == 200
?? header content-type == application/fhir+json;charset=utf-8
?? response.body  != null
?? js response.parsedBody.OperationOutcome.validationResults[0].engine == HAPI
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == ERROR
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == 1
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == 91

< fhir-fixture-shinny-bronx-unhappy-path.json

### /Bundle/$validate should validate fhir-fixture-shinny-healtheconnections-unhappy-path.json

POST {{hostName}}/Bundle/$validate HTTP/1.1
Content-Type: {{contentType}}
Accept : application/fhir+json;charset=utf-8
X-TechBD-Tenant-ID: {{TECH_BD_FHIR_SERVICE_QE_IDENTIFIER}}
X-TechBD-Interaction-Persistence-Strategy: {{TECH_BD_INTERACTION_PERSISTENCE_FS}}
?? status == 200
?? header content-type == application/fhir+json;charset=utf-8
?? response.body  != null
?? js response.parsedBody.OperationOutcome.validationResults[0].engine == HAPI
?? js response.parsedBody.OperationOutcome.resourceType == OperationOutcome
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].severity == FATAL
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.line == null
?? js response.parsedBody.OperationOutcome.validationResults[0].issues[0].location.column == null
< fhir-fixture-shinny-healtheconnections-unhappy-path.json

### /Bundle should validate and submit fhir-fixture-shinny-impl-guide-sample.json as HEALTHeLINK

POST {{hostName}}/Bundle/?qe=HEALTHELINK HTTP/1.1
X-TechBD-Interaction-Persistence-Strategy: {{TECH_BD_INTERACTION_PERSISTENCE_FS}}
?? status != 201
?? response.body  != null

< fhir-fixture-shinny-impl-guide-sample.json
